title: Rl242Dev - Apprenti Developpeur Web et Back-End
url: https://rl242dev.github.io/Rl242.github.io/
description: Mon nom est Robin, j'apprend le Front et Back-End en Autoditacte depuis 2 ans.
author: Rl242Dev
social: 
  name: Rl242Dev
  links: 
    - https://github.com/Rl242Dev